///////////////////////////////////////////////////////////
//  ICollisionControl.cs
//  Implementation of the Interface ICollisionControl
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////



using System.Collections.Generic;
using Sprites;

namespace Collision {
	public interface ICollisionControl  {

		/// 
		/// <param name="mSprites"></param>
		List<IEvent> Update();
	}//end ICollisionControl

}//end namespace CollitionControle