///////////////////////////////////////////////////////////
//  IEvent.cs
//  Implementation of the Interface IEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:45:09
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace Collision {
	public interface IEvent  {

		void HandleEvent();
	}//end IEvent

}//end namespace CollitionControle