///////////////////////////////////////////////////////////
//  IEvent.cs
//  Implementation of the Interface IEvent
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace Collision {
	public interface IEvent  {

	}//end IEvent

}//end namespace CollisionControl