///////////////////////////////////////////////////////////
//  MonsterDeathEvent.cs
//  Implementation of the Class MonsterDeathEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:45:29
//  Original author: Space-Punk
///////////////////////////////////////////////////////////



namespace Collision {
	public class MonsterDeathEvent : IEvent {

		public MonsterDeathEvent(){

		}

		~MonsterDeathEvent(){

		}

		public virtual void Dispose(){

		}

		public void HandleEvent(){

		}

	}//end MonsterDeathEvent

}//end namespace CollitionControle