///////////////////////////////////////////////////////////
//  MonsterEnviromentDetect.cs
//  Implementation of the Class MonsterEnviromentDetect
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using Collision;
using System.Collections.Generic;
using Sprites;
namespace Collision {
	public class MonsterEnviromentDetect : ICollisionDetect {

		public MonsterEnviromentDetect(){

		}


		/// 
		/// <param name="mSpriteCollection"></param>
		/// <param name="mSprite2"></param>
		/// <param name="mSprite1"></param>


        public IEvent Detect(ISpriteContainerCollision mSpriteCollection, ISprite mSprite2, ISprite mSprite1)
        {
            throw new System.NotImplementedException();
        }
    }//end MonsterEnviromentDetect

}//end namespace CollisionControl