///////////////////////////////////////////////////////////
//  MonsterDeathEvent.cs
//  Implementation of the Class MonsterDeathEvent
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using Sprites;
namespace Collision {
	public class MonsterDeathEvent : IEvent {

		public MonsterDeathEvent(ISprite mSprite, ISpriteContainerCollision mSpriteContainerCollision){

		}
	}//end MonsterDeathEvent

}//end namespace CollisionControl