///////////////////////////////////////////////////////////
//  PlayerEnviromentDetect.cs
//  Implementation of the Class PlayerEnviromentDetect
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:50
//  Original author: Space-Punk
///////////////////////////////////////////////////////////



using Sprites;
using System.Collections.Generic;
using Collision;
namespace Collision {
	public class PlayerEnviromentDetect : ICollisionDetect {

		public PlayerEnviromentDetect(){

		}



		/// 
		/// <param name="mSpriteCollection"></param>
		/// <param name="mSprite2"></param>
		/// <param name="mSprite1"></param>
		public IEvent Detect(ISpriteContainerCollision mSpriteCollection, ISprite mSprite2, ISprite mSprite1){

            throw new System.NotImplementedException();
		}

    }//end PlayerEnviromentDetect

}//end namespace CollisionControl