///////////////////////////////////////////////////////////
//  PlayerEnvironmentLeftEvent.cs
//  Implementation of the Class PlayerEnvironmentLeftEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:43:07
//  Original author: Filip
///////////////////////////////////////////////////////////





namespace Collision {
	public class PlayerEnvironmentLeftEvent : IEvent {

		public PlayerEnvironmentLeftEvent(){

		}

		~PlayerEnvironmentLeftEvent(){

		}

		public virtual void Dispose(){

		}

		public void HandleEvent(){

		}

	}//end PlayerEnvironmentLeftEvent

}//end namespace CollitionControle