///////////////////////////////////////////////////////////
//  PlayerEnvironmentTopEvent.cs
//  Implementation of the Class PlayerEnvironmentTopEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:43:47
//  Original author: Filip
///////////////////////////////////////////////////////////


using Microsoft.Xna.Framework;
using Sprites;

namespace Collision {
	public class PlayerEnvironmentTopEvent : IEvent {

        private SpritePlayer _playerSprite;
        private SpriteEnviroment _environmentSprite;

		public PlayerEnvironmentTopEvent(ISprite player, ISprite environmentSprite)
        {
            _playerSprite = (SpritePlayer)player;
		    _environmentSprite = (SpriteEnviroment)environmentSprite;
            HandleEvent();
		}

		public void HandleEvent()
		{
		    _playerSprite._isInAir = false;
		    int height = _playerSprite.MyRectangle.Height;
		    int width = _playerSprite.MyRectangle.Width;
		    int x = _playerSprite.MyRectangle.X;
            _playerSprite.MyRectangle = new Rectangle(x, _environmentSprite.MyRectangle.Y-height, width, height);
            //_playerSprite.Velocity = new Vector2(_playerSprite.Velocity.X, 0);
            _playerSprite.Position = new Vector2(_playerSprite.Position.X, _environmentSprite.MyRectangle.Top - height);
		}

	}//end PlayerEnvironmentTopEvent

}//end namespace CollitionControle