///////////////////////////////////////////////////////////
//  PlayerDeathEvent.cs
//  Implementation of the Class PlayerDeathEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:45:18
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


namespace Collision {
	public class PlayerDeathEvent : IEvent {

		public PlayerDeathEvent(){

		}

		~PlayerDeathEvent(){

		}

		public virtual void Dispose(){

		}

		public void HandleEvent(){

		}

	}//end PlayerDeathEvent

}//end namespace CollitionControle