///////////////////////////////////////////////////////////
//  PlayerEnvironmentBottomEvent.cs
//  Implementation of the Class PlayerEnvironmentBottomEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:43:49
//  Original author: Filip
///////////////////////////////////////////////////////////


using Microsoft.Xna.Framework;
using Sprites;

namespace Collision
{
    public class PlayerEnvironmentBottomEvent : IEvent
    {
        private SpritePlayer _playerSprite;
        private SpriteEnviroment _environmentSprite;

        public PlayerEnvironmentBottomEvent(ISprite player, ISprite environmentSprite)
        {
            _playerSprite = (SpritePlayer)player;
            _environmentSprite = (SpriteEnviroment)environmentSprite;
            HandleEvent();
        }

        private void HandleEvent()
        {
            //_playerSprite.IsInAir = false;
            _playerSprite.Velocity = new Vector2(_playerSprite.Velocity.X, 0);
            _playerSprite.Position = new Vector2(_playerSprite.Position.X, _environmentSprite.MyRectangle.Bottom);
        }

    }//end PlayerEnvironmentBottomEvent

}//end namespace CollitionControle