///////////////////////////////////////////////////////////
//  PlayerEnvironmentBottomEvent.cs
//  Implementation of the Class PlayerEnvironmentBottomEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:43:49
//  Original author: Filip
///////////////////////////////////////////////////////////


using Microsoft.Xna.Framework;
using Sprites;

namespace Collision
{
    public class PlayerEnvironmentBottomEvent : IEvent
    {
        private SpritePlayer _playerSprite;
        private SpriteEnviroment _environmentSprite;

        public PlayerEnvironmentBottomEvent(ISprite player, ISprite environmentSprite, ISpriteContainerCollision mReUpdate)
        {
            _playerSprite = (SpritePlayer)player;
            _environmentSprite = (SpriteEnviroment)environmentSprite;
            HandleEvent();
        }

        private void HandleEvent()
        {
            _playerSprite._isInAir = true;
            int height = _playerSprite.MyRectangle.Height;
            int width = _playerSprite.MyRectangle.Width;
            int x = _playerSprite.MyRectangle.X;
            _playerSprite.MyRectangle = new Rectangle(x, _environmentSprite.MyRectangle.Bottom , width, height);
            _playerSprite.Position = new Vector2(_playerSprite.Position.X, _environmentSprite.MyRectangle.Bottom );
            _playerSprite.Velocety = new Vector2(_playerSprite.Velocety.X, 0); 
        }

    }//end PlayerEnvironmentBottomEvent

}//end namespace CollitionControle