///////////////////////////////////////////////////////////
//  PlayerEnvironmentRightEvent.cs
//  Implementation of the Class PlayerEnvironmentRightEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:43:07
//  Original author: Filip
///////////////////////////////////////////////////////////





namespace Collision {
	public class PlayerEnvironmentRightEvent : IEvent {

		public PlayerEnvironmentRightEvent(){

		}

		~PlayerEnvironmentRightEvent(){

		}

		public virtual void Dispose(){

		}

		public void HandleEvent(){

		}

	}//end PlayerEnvironmentRightEvent

}//end namespace CollitionControle