///////////////////////////////////////////////////////////
//  PlayerEnvironmentLeftEvent.cs
//  Implementation of the Class PlayerEnvironmentLeftEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:43:07
//  Original author: Filip
///////////////////////////////////////////////////////////


using Microsoft.Xna.Framework;
using Sprites;

namespace Collision {
	public class PlayerEnvironmentLeftEvent : IEvent {

        private SpritePlayer _playerSprite;
        private SpriteEnviroment _environmentSprite;

        public PlayerEnvironmentLeftEvent(ISprite player, ISprite environmentSprite)
        {
            _playerSprite = (SpritePlayer)player;
            _environmentSprite = (SpriteEnviroment)environmentSprite;
            HandleEvent();
		}

		private void HandleEvent()
		{
            _playerSprite.Velocity = new Vector2(0, _playerSprite.Velocity.Y);
            _playerSprite.Position = new Vector2(_environmentSprite.MyRectangle.Left - _playerSprite.MyRectangle.Width, _playerSprite.Position.Y); // Moving the player "out" from the environment
		}

	}//end PlayerEnvironmentLeftEvent

}//end namespace CollitionControle