///////////////////////////////////////////////////////////
//  PlayerEnvironmentTopEvent.cs
//  Implementation of the Class PlayerEnvironmentTopEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:43:47
//  Original author: Filip
///////////////////////////////////////////////////////////





namespace Collision {
	public class PlayerEnvironmentTopEvent : IEvent {

		public PlayerEnvironmentTopEvent(){

		}

		~PlayerEnvironmentTopEvent(){

		}

		public virtual void Dispose(){

		}

		public void HandleEvent(){

		}

	}//end PlayerEnvironmentTopEvent

}//end namespace CollitionControle