///////////////////////////////////////////////////////////
//  PlayerEnvironmentBottomEvent.cs
//  Implementation of the Class PlayerEnvironmentBottomEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:43:49
//  Original author: Filip
///////////////////////////////////////////////////////////



namespace Collision {
	public class PlayerEnvironmentBottomEvent : IEvent {

		public PlayerEnvironmentBottomEvent(){

		}

		~PlayerEnvironmentBottomEvent(){

		}

		public virtual void Dispose(){

		}

		public void HandleEvent(){

		}

	}//end PlayerEnvironmentBottomEvent

}//end namespace CollitionControle