///////////////////////////////////////////////////////////
//  PlayerEnvironmentRightEvent.cs
//  Implementation of the Class PlayerEnvironmentRightEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:43:07
//  Original author: Filip
///////////////////////////////////////////////////////////


using Microsoft.Xna.Framework;
using Sprites;

namespace Collision {
	public class PlayerEnvironmentRightEvent : IEvent {

        private SpritePlayer _playerSprite;
        private SpriteEnviroment _environmentSprite;
		
        public PlayerEnvironmentRightEvent(ISprite player, ISprite environment)
        {
            _playerSprite = (SpritePlayer)player;
            _environmentSprite = (SpriteEnviroment)environment;
            HandleEvent();
		}

		public void HandleEvent()
		{
		    _playerSprite.Velocity = new Vector2(0,_playerSprite.Velocity.Y);
		    _playerSprite.Position = new Vector2(_environmentSprite.MyRectangle.Right, _playerSprite.Position.Y); // Moving the player "out" from the environment
		}

	}//end PlayerEnvironmentRightEvent

}//end namespace CollitionControle