///////////////////////////////////////////////////////////
//  PlayerDeathEvent.cs
//  Implementation of the Class PlayerDeathEvent
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:50
//  Original author: Space-Punk
///////////////////////////////////////////////////////////



using Sprites;
using Collision;
namespace Collision {
	public class PlayerDeathEvent : IEvent {

		public PlayerDeathEvent(ISprite mSprite, ISpriteContainerCollision mSpriteContainerCollision){

		}



	}//end PlayerDeathEvent

}//end namespace CollitionControle