///////////////////////////////////////////////////////////
//  PlayerEnvironmentTopEvent.cs
//  Implementation of the Class PlayerEnvironmentTopEvent
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 22:43:47
//  Original author: Filip
///////////////////////////////////////////////////////////


using Microsoft.Xna.Framework;
using Sprites;

namespace Collision {
	public class PlayerEnvironmentTopEvent : IEvent {

        private ISprite _playerSprite;
        private ISprite _environmentSprite;

		public PlayerEnvironmentTopEvent(ISprite player, ISprite environmentSprite)
        {
            _playerSprite = player;
		    _environmentSprite = environmentSprite;
            HandleEvent();
		}

		public void HandleEvent()
		{
		    //_playerSprite.IsInAir = true;
		    _playerSprite.Velocity = new Vector2(_playerSprite.Velocity.X, 0);
            _playerSprite.Position = new Vector2(_playerSprite.Position.X, _environmentSprite.MyRectangle.Bottom - _playerSprite.MyRectangle.Height);
		}

	}//end PlayerEnvironmentTopEvent

}//end namespace CollitionControle