///////////////////////////////////////////////////////////
//  IPlayerDataGame.cs
//  Implementation of the Interface IPlayerDataGame
//  Generated by Enterprise Architect
//  Created on:      09-maj-2013 09:35:38
//  Original author: Filip
///////////////////////////////////////////////////////////




public interface IPlayerDataGame  {

	int GetHighscore();

	string GetPlayerName();
}//end IPlayerDataGame