///////////////////////////////////////////////////////////
//  PlayerData.cs
//  Implementation of the Class PlayerData
//  Generated by Enterprise Architect
//  Created on:      09-maj-2013 09:35:37
//  Original author: Filip
///////////////////////////////////////////////////////////




public class PlayerData : IPlayerData, IPlayerDataGame
{

    public int Highscore { get; set; }
    private string _playername = "No Name Specified";

	public PlayerData()
	{
	    Highscore = 0;
	    GameRunning = true;
	}
    public bool GameRunning { get; set; }

	


	public string GetPlayerName(){

		return _playername;
	}

	/// 
	/// <param name="highscore"></param>
	public void SetHighscore(int highscore)
	{
	    Highscore = highscore;
	}

	/// 
	/// <param name="name"></param>
	public void SetPlayerName(string name)
	{
	    _playername = name;
	}

}//end PlayerData