///////////////////////////////////////////////////////////
//  PlayerData.cs
//  Implementation of the Class PlayerData
//  Generated by Enterprise Architect
//  Created on:      09-maj-2013 09:35:37
//  Original author: Filip
///////////////////////////////////////////////////////////




public class PlayerData : IPlayerData, IPlayerDataGame
{

    private int _highscore=0;
    private string _playername = "No Name Specified";

	public PlayerData(){

	}

	
	public int GetHighscore(){

		return _highscore;
	}

	public string GetPlayerName(){

		return _playername;
	}

	/// 
	/// <param name="highscore"></param>
	public void SetHighscore(int highscore)
	{
	    _highscore = highscore;
	}

	/// 
	/// <param name="name"></param>
	public void SetPlayerName(string name)
	{
	    _playername = name;
	}

}//end PlayerData