///////////////////////////////////////////////////////////
//  GameStateC.cs
//  Implementation of the Class GameStateC
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:51
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace GameState {
	public class GameStateC : IGameState, IGameStateEvent, IGameStateLevel, IGameStateGameRunning
	{
	    private int _lifes;
        private static readonly object lockObject = new object();
	    private bool _isGameRunning = false;
	    private int _gameLevel;
		public GameStateC(){

		}

		/// 
		/// <param name="mScore"></param>
		public void AddScore(int mScore)
		{
		    _score += mScore;
		}

		public int GameLevel{
			get{
				return _gameLevel;
			}
			set{
				_gameLevel = value;
			}
		}

		public bool IsGameRunning{
			get{
			    lock (this)
			    {
                    return _isGameRunning;
			    }			
			}
            set
            {
                lock (this)
                {
                    _isGameRunning = value;
                }
            }
		}

	    private int _score;
	    public int Lifes { set; get; }
        
        int IGameStateLevel.Score { get { return _score; } set { _score = value; } }
        int IGameState.Score { get { return _score; } set { _score = value; } }

	    public void LoseLife(){

		}

    }//end GameStateC

}//end namespace GameStateC