///////////////////////////////////////////////////////////
//  IGameState.cs
//  Implementation of the Interface IGameState
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:51
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace GameState {
	public interface IGameState  {

		int GameLevel{
			get;
			set;
		}

		bool GameRunning{
			get;
			set;
		}

        int Score
        {
            get;  }
	}//end IGameState

}//end namespace GameState