///////////////////////////////////////////////////////////
//  IGameStateLevel.cs
//  Implementation of the Interface IGameStateLevel
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:51
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace GameState {
	public interface IGameStateLevel  {

		int Lifes{
			set;
		}

		int Score{
			get;
			set;
		}
	}//end IGameStateLevel

}//end namespace GameStateC