///////////////////////////////////////////////////////////
//  IGameStateEvent.cs
//  Implementation of the Interface IGameStateEvent
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:51
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace GameState {
	public interface IGameStateEvent  {

		/// 
		/// <param name="mScore"></param>
		void AddScore(int mScore);

		void LoseLife();
	}//end IGameStateEvent

}//end namespace GameState