///////////////////////////////////////////////////////////
//  ClientCommunication_Level.cs
//  Implementation of the Interface ClientCommunication_Level
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 21:51:57
//  Original author: Filip
///////////////////////////////////////////////////////////




public interface ClientCommunication_Level  {

	/// 
	/// <param name="messag"></param>
	void Send(string messag);
}//end ClientCommunication_Level