///////////////////////////////////////////////////////////
//  GameClientProtocol.cs
//  Implementation of the Class GameClientProtocol
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 21:51:56
//  Original author: Filip
///////////////////////////////////////////////////////////




public class GameClientProtocol {

	public GameClientProtocol(){

	}

	~GameClientProtocol(){

	}

	public virtual void Dispose(){

	}

}//end GameClientProtocol