///////////////////////////////////////////////////////////
//  ClientCommunication_Game.cs
//  Implementation of the Interface ClientCommunication_Game
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 21:51:56
//  Original author: Filip
///////////////////////////////////////////////////////////



namespace ClientCommunication
{
    public interface IClientCommunication_Game
    {

        void Send(string message);
    }

//end ClientCommunication_Game
}