///////////////////////////////////////////////////////////
//  ClientCommunication_Game.cs
//  Implementation of the Interface ClientCommunication_Game
//  Generated by Enterprise Architect
//  Created on:      04-maj-2013 21:51:56
//  Original author: Filip
///////////////////////////////////////////////////////////




public interface ClientCommunication_Game  {

	/// 
	/// <param name="pipeIn"></param>
	/// <param name="pipeOut"></param>
	bool Connect(string pipeIn, string pipeOut);

	string Receive();
}//end ClientCommunication_Game