///////////////////////////////////////////////////////////
//  IMessageHandler.cs
//  Implementation of the Interface IMessageHandler
//  Generated by Enterprise Architect
//  Created on:      07-maj-2013 09:39:12
//  Original author: Filip
///////////////////////////////////////////////////////////


using SuperIHABrothers.Sprite;

namespace ClientCommunication
{
	public interface IMessageHandler  {

		/// 
		/// <param name="mContainer"></param>
		void SetContainer(ISpriteContainerMessage mContainer);
	}//end IMessageHandler

}//end namespace DampCommunication