///////////////////////////////////////////////////////////
//  Anchor.cs
//  Implementation of the Class Anchor
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using Sprites;
namespace Sprites {
	public class Anchor : IAnchor, IAnchorPlayer, IAnchorUpdate {

		private Vector2D Position;

		public Anchor(){

		}

		~Anchor(){

		}

		public virtual void Dispose(){

		}

		public int Position{
			get{
				return Position;
			}
		}

		/// 
		/// <param name="mSpeed"></param>
		public void SetSpeed(int mSpeed){

		}

		public void Update(){

		}

		public int Speed{
			set{
				Speed = value;
			}
		}

	}//end Anchor

}//end namespace Sprites