///////////////////////////////////////////////////////////
//  IAnchorUpdate.cs
//  Implementation of the Interface IAnchorUpdate
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using Microsoft.Xna.Framework;

namespace Sprites {
	public interface IAnchorUpdate  {

		void Update(GameTime time);
	}//end IAnchorUpdate

}//end namespace Sprites