///////////////////////////////////////////////////////////
//  IAnchor.cs
//  Implementation of the Interface IAnchor
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace Sprites {
	public interface IAnchor  {

		2DVector Position{
			get;
		}
	}//end IAnchor

}//end namespace Sprites