///////////////////////////////////////////////////////////
//  IAnchorPlayer.cs
//  Implementation of the Interface IAnchorPlayer
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace Sprites {
	public interface IAnchorPlayer  {

		int Speed{
			set;
		}
	}//end IAnchorPlayer

}//end namespace Sprites