///////////////////////////////////////////////////////////
//  IAnchor.cs
//  Implementation of the Interface IAnchor
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using Microsoft.Xna.Framework;

namespace Sprites {
	public interface IAnchor  {

        Vector2 Position { get; set; }
	}//end IAnchor

}//end namespace Sprites