///////////////////////////////////////////////////////////
//  ISpriteContainerCollision.cs
//  Implementation of the Interface ISpriteContainerCollision
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using Collision;
using Microsoft.Xna.Framework;

namespace Sprites {
	public interface ISpriteContainerCollision  {

		/// 
		/// <param name="mSprite"></param>
		void AddDeathAnimation(ISprite mSprite);

		/// 
		/// <param name="mSprite"></param>
		void RemoveMonster(ISprite mSprite);

	    void RemovePlayer(ISprite mSprite);

<<<<<<< HEAD
	    void ReUpdate();
=======
	    void ReUpdate(Vector2 mPos);
>>>>>>> 634d738f07c5e1c11ac4aef98775b186a102ba3f

		List<List<ISprite>> SpriteList{
			get;
		}

        
	}//end ISpriteContainerCollision

}//end namespace Sprites