///////////////////////////////////////////////////////////
//  ISpriteContainer.cs
//  Implementation of the Interface ISpriteContainer
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace Sprites {
	public interface ISpriteContainer  {


		void Update(GameTime time);
	    void Draw(SpriteBatch spriteBatch);
	}//end ISpriteContainer

}//end namespace Sprites