///////////////////////////////////////////////////////////
//  ISpriteContainerCollition.cs
//  Implementation of the Interface ISpriteContainerCollition
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using CollitionControle;
namespace Sprites {
	public interface ISpriteContainerCollition  {

		/// 
		/// <param name="mSprite"></param>
		void AddSprite(ISprite mSprite);

		/// 
		/// <param name="mSprite"></param>
		void RemoveSprite(ISprite mSprite);

		List<ISprite> SpriteList{
			get;
		}
	}//end ISpriteContainerCollition

}//end namespace Sprites