///////////////////////////////////////////////////////////
//  ISprite.cs
//  Implementation of the Interface ISprite
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////



using Microsoft.Xna.Framework;
namespace Sprites {
	public interface ISprite  {

		void Draw();

		Vector2 MyPosition{
			get;
			set;
		}

        Rectangle MyRectangle
        {
            get; set; }

		void Update();
	}//end ISprite

}//end namespace Sprites