///////////////////////////////////////////////////////////
//  ISprite.cs
//  Implementation of the Interface ISprite
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace Sprites {
	public interface ISprite  {

		void Draw();

		Vector2 MyPosition{
			get;
			set;
		}

		Rectangle MyRectangle{
			get;
		}

		void Update();
	}//end ISprite

}//end namespace Sprites