///////////////////////////////////////////////////////////
//  ISpriteContainerCollision.cs
//  Implementation of the Interface ISpriteContainerCollision
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using Collision;
namespace Sprites {
	public interface ISpriteContainerCollision  {

		/// 
		/// <param name="mSprite"></param>
		void AddDeathAnimation(ISprite mSprite);

		/// 
		/// <param name="mSprite"></param>
		void RemoveMonster(ISprite mSprite);

	    void RemovePlayer(ISprite mSprite);

		List<List<ISprite>> SpriteList{
			get;
		}

        
	}//end ISpriteContainerCollision

}//end namespace Sprites