///////////////////////////////////////////////////////////
//  ISpriteContainer.cs
//  Implementation of the Interface ISpriteContainer
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using Microsoft.Xna.Framework;

namespace Sprites {
	public interface ISpriteContainer  {

		List<ISprite> SpriteList{
			set;
		}

		void Update(GameTime time);
	}//end ISpriteContainer

}//end namespace Sprites