///////////////////////////////////////////////////////////
//  SpriteDeathAnimaiton.cs
//  Implementation of the Class SpriteDeathAnimaiton
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using Sprites;
namespace Sprites {
	public class SpriteDeathAnimaiton : ISprite {

		public Sprites.IAnchor m_IAnchor;

		public SpriteDeathAnimaiton(){

		}

		~SpriteDeathAnimaiton(){

		}

		public virtual void Dispose(){

		}

		public void Draw(){

		}

		public Vector2 MyPosition{
			get{
				return MyPosition;
			}
			set{
				MyPosition = value;
			}
		}

		public Rectangle MyRectangle{
			get{
				return MyRectangle;
			}
		}

		public void Update(){

		}

	}//end SpriteDeathAnimaiton

}//end namespace Sprites