///////////////////////////////////////////////////////////
//  SpriteBackground.cs
//  Implementation of the Class SpriteBackground
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Sprites;
namespace Sprites {
	public class SpriteBackground : ISprite {

        //Generel Atributes
        public Vector2 Position { get; set; }
        private Vector2 _AnchorOffset;
        public Rectangle MyRectangle { get; set; }
	    public Vector2 Velocity { get; set; }
	    public bool _isInAir { get; set; }
	    private IAnchor _Anchor;
        private int _FrameHeight;
        private int _FrameWidth;
        private Texture2D _texture2D;

        //Moving Atributes
        public Vector2 Velocety { get { return _velocety; } set { _velocety = value; } }
        private Vector2 _velocety;
	    private int _distance; //Distance form forground to the background

        public SpriteBackground()
        {

        }
	    public void Draw(SpriteBatch spriteBatch)
	    {
	        throw new System.NotImplementedException();
	    }


	    public void Update(GameTime time)
	    {
	        throw new System.NotImplementedException();
	    }

	    public void UpdatePosition()
	    {
	        
	    }
	}//end SpriteBackground

}//end namespace Sprites