///////////////////////////////////////////////////////////
//  SpriteMonster.cs
//  Implementation of the Class SpriteMonster
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:22
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using Sprites;
namespace Sprites {
	public class SpriteMonster : ISprite {

		public Sprites.IAnchor m_IAnchor;

		public SpriteMonster(){

		}

		~SpriteMonster(){

		}

		public virtual void Dispose(){

		}

		public void Draw(){

		}

		public Vector2 MyPosition{
			get{
				return MyPosition;
			}
			set{
				MyPosition = value;
			}
		}

		public Rectangle MyRectangle{
			get{
				return MyRectangle;
			}
		}

		public void Update(){

		}

	}//end SpriteMonster

}//end namespace Sprites