///////////////////////////////////////////////////////////
//  SpriteContainer.cs
//  Implementation of the Class SpriteContainer
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace Sprites {
    enum listTypes
    {
        Player = 0,
        Monster = 1,
        Envirinment = 2,
        Background = 3,
        DeathAnimation = 4
    }
	public class SpriteContainer : ISpriteContainer, ISpriteContainerCollision {

		public Sprites.IAnchorUpdate _IAnchorUpdate;
		public Sprites.ISprite _ISprite;
	    private List<List<ISprite>> _spriteList;


	    public void AddDeathAnimation(ISprite mSprite)
	    {
	        throw new System.NotImplementedException();
	    }

	    public void RemoveMonster(ISprite mSprite)
	    {
	        throw new System.NotImplementedException();
	    }

	    public void RemovePlayer(ISprite mSprite)
	    {
	        throw new System.NotImplementedException();
	    }

	    List<List<ISprite>> ISpriteContainerCollision.SpriteList { get { return _spriteList; } }
       
	    private IAnchorUpdate _anchor;


		public SpriteContainer(List<List<ISprite>> mList, IAnchorUpdate mAnchor)
		{
		    _spriteList = mList;
		    _anchor = mAnchor;
		}



		

	    


	    public void Update(GameTime time)
	    {
	        _anchor.Update(time);
	        foreach (var _list in _spriteList)
	        {
	            foreach (var sprite in _list)
	            {
	                sprite.Update(time);
	            }
	        }
	    }

	    public void Draw(SpriteBatch spriteBatch)
	    {
            foreach (var _list in _spriteList)
            {
                foreach (var sprite in _list)
                {
                    sprite.Draw(spriteBatch);
                }
            }
	    }
	}//end SpriteContainer

}//end namespace Sprites