///////////////////////////////////////////////////////////
//  SpriteDeathAnimaiton.cs
//  Implementation of the Class SpriteDeathAnimaiton
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using System;
using Microsoft.Xna.Framework;
using Sprites;
namespace Sprites {
	public class SpriteDeathAnimaiton : ISprite {

		public Sprites.IAnchor m_IAnchor;
        public Vector2 MyPosition { get; set; }
        public Rectangle MyRectangle { get; set; }

		public SpriteDeathAnimaiton(){
            throw new NotImplementedException();
		}


		public void Draw(){
            throw new NotImplementedException();
		}




	    public void Update(){
            throw new NotImplementedException();
		}

	}//end SpriteDeathAnimaiton

}//end namespace Sprites