///////////////////////////////////////////////////////////
//  SpriteContainer.cs
//  Implementation of the Class SpriteContainer
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:21
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using Sprites;
namespace Sprites {
	public class SpriteContainer : ISpriteContainer, ISpriteContainerCollition {

		public Sprites.IAnchorUpdate m_IAnchorUpdate;
		public Sprites.ISprite m_ISprite;

		public SpriteContainer(){

		}

		~SpriteContainer(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="mStrite"></param>
		public void AddSprite(ISprite mStrite){

		}

		/// 
		/// <param name="mSprite"></param>
		public void RemoveSprite(ISprite mSprite){

		}

		public List<ISprite> ISpriteContainer.SpriteList{
			set{
				SpriteList = value;
			}
		}

		public void Update(){

		}

		public List<ISprite> ISpriteContainerCollition.SpriteList{
			get{
				return SpriteList;
			}
		}

	}//end SpriteContainer

}//end namespace Sprites