///////////////////////////////////////////////////////////
//  SpritePlayer.cs
//  Implementation of the Class SpritePlayer
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:22
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using System;
using Microsoft.Xna.Framework;
using Sprites;
namespace Sprites {
	public class SpritePlayer : ISprite {

		public Sprites.IAnchorPlayer m_IAnchorPlayer;
        public Vector2 MyPosition { get; set; }
        public Rectangle MyRectangle { get; set; }

		public SpritePlayer(){
            throw new NotImplementedException();
		}



		public void Draw(){
            throw new NotImplementedException();
		}




	    public void Update(){
            throw new NotImplementedException();
		}

	}//end SpritePlayer

}//end namespace Sprites