///////////////////////////////////////////////////////////
//  SpriteMonster.cs
//  Implementation of the Class SpriteMonster
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:22
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using System;
using Microsoft.Xna.Framework;
using Sprites;
namespace Sprites {
	public class SpriteMonster : ISprite {

		public Sprites.IAnchor m_IAnchor;
        public Vector2 MyPosition { get; set; }
        public Rectangle MyRectangle { get; set; }

		public SpriteMonster(){
            throw new NotImplementedException();
		}


		public void Draw(){
            throw new NotImplementedException();
		}




	    public void Update(){
            throw new NotImplementedException();
		}

	}//end SpriteMonster

}//end namespace Sprites