///////////////////////////////////////////////////////////
//  SpriteEnviroment.cs
//  Implementation of the Class SpriteEnviroment
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:22
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using Sprites;
namespace Sprites {
	public class SpriteEnviroment : ISprite {

		public Sprites.IAnchor m_IAnchor;

		public SpriteEnviroment(){

		}

		~SpriteEnviroment(){

		}

		public virtual void Dispose(){

		}

		public void Draw(){

		}

		public Vector2 MyPosition{
			get{
				return MyPosition;
			}
			set{
				MyPosition = value;
			}
		}

		public Rectangle MyRectangle{
			get{
				return MyRectangle;
			}
		}

		public void Update(){

		}

	}//end SpriteEnviroment

}//end namespace Sprites