///////////////////////////////////////////////////////////
//  SpriteEnviroment.cs
//  Implementation of the Class SpriteEnviroment
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:48:22
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Sprites;
namespace Sprites {
	public class SpriteEnviroment : ISprite 
    {
        //Generel Atrbutes
        public Vector2 Position { get; set; }
        public Rectangle MyRectangle { get; set; }
	    private IAnchor _anchor;
        private Vector2 _AnchorOffset;
	    private Texture2D _texture2D;
	    private int _FrameHeight;
	    private int _FrameWidth;

        public SpriteEnviroment(Texture2D mTexture2D, Vector2 mAnchorOffset, int mFrameHeight, int mFrameWidth, IAnchor mAnchor)
        {
            throw new NotImplementedException();
        }

	    public void Draw(SpriteBatch spriteBatch)
	    {
	        throw new NotImplementedException();
	    }

	    
	    public void Update(GameTime time)
	    {
	        throw new NotImplementedException();
	    }



	}//end SpriteEnviroment

}//end namespace Sprites