///////////////////////////////////////////////////////////
//  Game.cs
//  Implementation of the Class Game
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:49:45
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using Collision;
using GameState;
using GameControle;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace GameControle {
	public class Game {

		private GameState.IGameState m_IGameState;
		private GameControle.ILevel m_ILevel;
	    private IKeybordInput mInput;
	    private IKeyboardUpdate _keyboardUpdate;
	    private IGameState _gameState;

		public Game(IFactoryLevel factoryLevel, IGameState gameState, IKeybordInput keyInput, IKeyboardUpdate keyboardUpdate)
		{
		    _gameState = gameState;
		    mInput = keyInput;
		    _keyboardUpdate = keyboardUpdate;
		    m_ILevel = factoryLevel.GetLevelOne(mInput);
		}

        public void Update(GameTime time)
        {
            _keyboardUpdate.Update();
            m_ILevel.Update(time);
        }

        public void Draw(SpriteBatch spriteBatch)
        {
            m_ILevel.Draw(spriteBatch);
        }



	}//end Game

}//end namespace GameControle