///////////////////////////////////////////////////////////
//  Game.cs
//  Implementation of the Class Game
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:49:45
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using GameState;
using GameControle;
using Microsoft.Xna.Framework;

namespace GameControle {
	public class Game {

		public GameState.IGameState m_IGameState;
		public GameControle.ILevel m_ILevel;
	    private KeybordInput mInput;
        

		public Game(){

		}

        public void Update(GameTime time)
        {
            mInput.Update();
            m_ILevel.Update(time);
        }



	}//end Game

}//end namespace GameControle