///////////////////////////////////////////////////////////
//  ILevel.cs
//  Implementation of the Interface ILevel
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:49:45
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace GameControle {
	public interface ILevel  {

		void Draw();

		void Update();
	}//end ILevel

}//end namespace GameControle