///////////////////////////////////////////////////////////
//  ILevel.cs
//  Implementation of the Interface ILevel
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:49:45
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace GameControle {
	public interface ILevel  {

		void Draw(SpriteBatch spriteBatch);

		void Update(GameTime time);
	}//end ILevel

}//end namespace GameControle