///////////////////////////////////////////////////////////
//  Level1.cs
//  Implementation of the Class Level1
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:49:45
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using CollitionControle;
using GameControle;
using Sprites;
using EventHandling;
using GameState;
namespace GameControle {
	public class Level1 : ILevel {

		public CollitionControle.IColitionControle m_IColitionControle;
		public Sprites.ISpriteContainer m_ISpriteContainer;
		public EventHandling.IEventHandlerMain m_IEventHandlerMain;
		public GameState.IGameStateLevel m_IGameStateLevel;

		public Level1(){

		}


		public void Draw(){

		}

		public void NewLevel(){

		}

		public void Update(){

		}

	}//end Level1

}//end namespace GameControle