///////////////////////////////////////////////////////////
//  PlayerDeathEvent.cs
//  Implementation of the Class PlayerDeathEvent
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:50
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using CollitionControle;
namespace CollitionControle {
	public class PlayerDeathEvent : IEvent {

		public PlayerDeathEvent(){

		}

		~PlayerDeathEvent(){

		}

		public virtual void Dispose(){

		}

	}//end PlayerDeathEvent

}//end namespace CollitionControle