///////////////////////////////////////////////////////////
//  ColitionControle.cs
//  Implementation of the Class ColitionControle
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using CollitionControle;
namespace CollitionControle {
	public class ColitionControle : IColitionControle {

		public CollitionControle.IColitionDetect m_IColitionDetect;

		public ColitionControle(){

		}

		~ColitionControle(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="mSprites"></param>
		public List<IEvent> Update(List<ISprites> mSprites){

			return null;
		}

	}//end ColitionControle

}//end namespace CollitionControle