///////////////////////////////////////////////////////////
//  ColitionControle.cs
//  Implementation of the Class ColitionControle
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using CollitionControle;
using System.Collections.Generic;
using Sprites;

namespace CollitionControle {
	public class ColitionControle : IColitionControle {

		private IColitionDetect _IColitionDetect;

		public ColitionControle(IColitionDetect mColitionDetect)
		{
		    _IColitionDetect = mColitionDetect;
		}


		/// 
		/// <param name="mSprites"></param>
        public List<IEvent> Update(List<ISprite> mSprites)
        {
            throw new System.NotImplementedException();
        }
    }//end ColitionControle

}//end namespace CollitionControle