///////////////////////////////////////////////////////////
//  IColitionDetect.cs
//  Implementation of the Interface IColitionDetect
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////



using Sprites;
using System.Collections.Generic;
namespace CollitionControle {
	public interface IColitionDetect  {

		/// 
		/// <param name="mSpriteCollection"></param>
		/// <param name="mSprite2"></param>
		/// <param name="mSprite1"></param>
		List<IEvent> Detect(ISpriteContainerCollition mSpriteCollection, ISprite mSprite2, ISprite mSprite1);
	}//end IColitionDetect

}//end namespace CollitionControle