///////////////////////////////////////////////////////////
//  IColitionControle.cs
//  Implementation of the Interface IColitionControle
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




namespace CollitionControle {
	public interface IColitionControle  {

		/// 
		/// <param name="mSprites"></param>
		List<IEvent> Update(List<ISprites> mSprites);
	}//end IColitionControle

}//end namespace CollitionControle