///////////////////////////////////////////////////////////
//  MonsteDeathEvent.cs
//  Implementation of the Class MonsteDeathEvent
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using CollitionControle;
namespace CollitionControle {
	public class MonsteDeathEvent : IEvent {

		public MonsteDeathEvent(){

		}

		~MonsteDeathEvent(){

		}

		public virtual void Dispose(){

		}

	}//end MonsteDeathEvent

}//end namespace CollitionControle