///////////////////////////////////////////////////////////
//  MonsteDeathEvent.cs
//  Implementation of the Class MonsteDeathEvent
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using Sprites;
namespace CollitionControle {
	public class MonsteDeathEvent : IEvent {

		public MonsteDeathEvent(ISprite mSprite, ISpriteContainerCollition mSpriteContainerCollition){

		}
	}//end MonsteDeathEvent

}//end namespace CollitionControle