///////////////////////////////////////////////////////////
//  MonsterEnviromentDetect.cs
//  Implementation of the Class MonsterEnviromentDetect
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:49
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using CollitionControle;
namespace CollitionControle {
	public class MonsterEnviromentDetect : IColitionDetect {

		public MonsterEnviromentDetect(){

		}

		~MonsterEnviromentDetect(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="mSpriteCollection"></param>
		/// <param name="mSprite2"></param>
		/// <param name="mSprite1"></param>
		public List<IEvent> Detect(ISpriteCollectionColition mSpriteCollection, ISprite mSprite2, ISprite mSprite1){

			return null;
		}

	}//end MonsterEnviromentDetect

}//end namespace CollitionControle