///////////////////////////////////////////////////////////
//  EventHandlerPlayerDeath.cs
//  Implementation of the Class EventHandlerPlayerDeath
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:26
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using EventHandling;
using GameState;
namespace EventHandling {
	public class EventHandlerPlayerDeath : IEventHandlerSpecefic {

		public GameState.IGameStateEvent m_IGameStateEvent;

		public EventHandlerPlayerDeath(){

		}

		~EventHandlerPlayerDeath(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="mEvent"></param>
		public void HandleEvent(IEvent mEvent){

		}

	}//end EventHandlerPlayerDeath

}//end namespace EventHandling