///////////////////////////////////////////////////////////
//  EventHandlerMain.cs
//  Implementation of the Class EventHandlerMain
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:26
//  Original author: Space-Punk
///////////////////////////////////////////////////////////




using EventHandling;
namespace EventHandling {
	public class EventHandlerMain : IEventHandlerMain {

		public EventHandling.IEventHandlerSpecefic m_IEventHandlerSpecefic;

		public EventHandlerMain(){

		}

		~EventHandlerMain(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="mEventList"></param>
		public void HandleEvents(List<IEvent> mEventList){

		}

	}//end EventHandlerMain

}//end namespace EventHandling