///////////////////////////////////////////////////////////
//  IEventHandlerSpecefic.cs
//  Implementation of the Interface IEventHandlerSpecefic
//  Generated by Enterprise Architect
//  Created on:      16-apr-2013 11:50:26
//  Original author: Space-Punk
///////////////////////////////////////////////////////////


using Collision;

namespace EventHandling {
	public interface IEventHandlerSpecefic  {

		/// 
		/// <param name="mEvent"></param>
		void HandleEvent(IEvent mEvent);
	}//end IEventHandlerSpecefic

}//end namespace EventHandling